### ISSUE TITLE
Using the code with merge to master events.

### ISSUE THREAD

**Issue by mycaule** [karsov/gh-actions#5]
Hello,

First thanks for your code snippet, it is really useful.

I was wondering how to make it work also with push events on master after merging a pull request, replacing the header section with

```yaml
on:
   push:
      branches: master
```

then in the changedfile action I tried to replace these variables with

```
github.event.pull_request.base.sha
-> github.event.push.base.sha
```

but when merging to master it does not detect the folder changes.

Any idea how to make it work ?

**Comment by karsov** [comment]
The only changes you need to do are to replace all occurrences of `github.event.pull_request.head.sha` with `github.event.after` and all occurrences of `github.event.pull_request.base.sha` with `github.event.before`.

You can check the properties of the push event here (it is different than the pull_request): https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push

P.S. To be on the safe side, I would recommend running all tests on merge into the main branch and not filtering only the changed folders.
